version: '3.1'

services:

  postgres_catalogue: # https://hub.docker.com/_/postgres
    image: postgres:16
    restart: always
    container_name: catalogue-db
    environment:
      POSTGRES_DB: catalogue_db
      POSTGRES_USER: catalogue
      POSTGRES_PASSWORD: catalogue
    ports:
      - 5432:5432

  mongo: # https://hub.docker.com/_/mongo
    image: mongo:7
    restart: always
    container_name: feedback-db
#    environment:
#      MONGO_INITDB_DATABASE: feedback_db
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017