spring:
  application:
    name: manager-app
  datasource:
    url: jdbc:postgresql://localhost:5433/manager_db
    username: manager
    password: manager
  flyway:
    schemas:
      - public
      - user_management

selmag:
  services:
    catalogue:
      uri: http://localhost:8081
      username: catalogue_service_user
      password: password