spring:
  application:
    name: manager-app
  boot:
    admin:
      client:
        url: http://localhost:8085
        instance:
          name: ${spring.application.name}
          service-host-type: ip
          service-url: http://localhost:8080
        enabled: true # default
  security:
    oauth2:
      client:
        provider: # Предоставляют ключи доступа
          keycloak:
            issuer-uri: http://localhost:8082/realms/selmag
            user-name-attribute: preferred_username
        registration: # Регистрация клиента
          keycloak:
            client-id: manager-app
            client-secret: 3HwpiJHJ4adsxBRv1qnW1RLeml82y2V2
            scope:
              - openid
              - edit_catalogue
              - view_catalogue
              - microprofile-jwt
          metrics:
            provider: keycloak
            client-id: manager-app-metrics-client
            client-secret: CzGP1zPoCf08CrpNfZKWwzNY2kQVdB3W
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
      resourceserver:
            jwt:
              issuer-uri: http://localhost:8082/realms/selmag

selmag:
  services:
    catalogue:
      uri: http://localhost:8081
      registration-id: keycloak

server:
  port: 8080

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'