spring:
  application:
    name: catalogue-service
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue_db
    username: catalogue
    password: catalogue
  flyway:
    schemas:
      - public
      - catalogue
  security:
    user:
      name: catalogue_service_user
      password: password
      roles:
        - SERVICE
  jpa:
    show-sql: true
server:
  port: 8081
#logging:
#  level:
#    sql: info