server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native: # Используй специальный native профиль
          search-locations: file:///${user.home}\IdeaProjects\selmag\config\cloud\{application}\{profile}