server:
  port: 8084
  forward-headers-strategy: framework

spring:
  application:
    name: feedback-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:pass@localhost:8888